export const pizzas = [
  { id:'margherita', name:'Classic Margherita', category:'Classic', price:10.9, image:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80', description:'A timeless Neapolitan favorite with bright, simple flavors.', ingredients:['San Marzano tomato','Mozzarella','Fresh basil','Olive oil'], badge:'Bestseller' },
  { id:'pepperoni', name:'Double Pepperoni', category:'Meat', price:13.9, image:'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=900&q=80', description:'Generous layers of crispy pepperoni and molten mozzarella.', ingredients:['Tomato sauce','Pepperoni','Mozzarella','Oregano'], badge:'Popular' },
  { id:'truffle', name:'Truffle Mushroom', category:'Vegetarian', price:15.5, image:'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=80', description:'Earthy mushrooms lifted by a touch of fragrant truffle oil.', ingredients:['White sauce','Mushrooms','Mozzarella','Truffle oil'], badge:'Chef pick' },
  { id:'bbq-chicken', name:'Smoky BBQ Chicken', category:'Meat', price:14.5, image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80', description:'Tender chicken, smoky barbecue sauce, onions and sweet corn.', ingredients:['BBQ sauce','Chicken','Red onion','Sweet corn'], badge:'' },
  { id:'veggie-garden', name:'Garden Veggie', category:'Vegetarian', price:12.9, image:'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=80', description:'A colorful harvest of roasted vegetables on a tomato base.', ingredients:['Bell peppers','Olives','Mushrooms','Red onion'], badge:'' },
  { id:'four-cheese', name:'Four Cheese', category:'Classic', price:13.5, image:'https://images.unsplash.com/photo-1548365328-8b849e6f9b40?auto=format&fit=crop&w=900&q=80', description:'Creamy, stretchy and gloriously cheesy.', ingredients:['Mozzarella','Gorgonzola','Parmesan','Ricotta'], badge:'' },
  { id:'spicy-diavola', name:'Spicy Diavola', category:'Meat', price:14.9, image:'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=80', description:'Hot salami, chili and jalapeños for a fiery finish.', ingredients:['Spicy salami','Jalapeños','Chili flakes','Mozzarella'], badge:'Hot' },
  { id:'hawaiian', name:'Hawaiian Sunshine', category:'Meat', price:13.2, image:'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=900&q=80', description:'A sweet-and-savory classic with roasted pineapple.', ingredients:['Ham','Pineapple','Mozzarella','Tomato sauce'], badge:'' },
  { id:'pesto', name:'Pesto Primavera', category:'Vegetarian', price:14.2, image:'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=900&q=80', description:'Basil pesto, sun-dried tomatoes and creamy feta.', ingredients:['Basil pesto','Feta','Cherry tomatoes','Rocket'], badge:'' },
  { id:'seafood', name:'Mediterranean Seafood', category:'Specialty', price:16.9, image:'https://images.unsplash.com/photo-1566843972142-a7fcb70de55a?auto=format&fit=crop&w=900&q=80', description:'A coastal blend of prawns, calamari and garlic.', ingredients:['Prawns','Calamari','Garlic','Parsley'], badge:'New' },
  { id:'prosciutto', name:'Prosciutto & Rocket', category:'Specialty', price:16.2, image:'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?auto=format&fit=crop&w=900&q=80', description:'Silky prosciutto and peppery rocket, finished after baking.', ingredients:['Prosciutto','Rocket','Parmesan','Mozzarella'], badge:'' },
  { id:'vegan', name:'Vegan Verde', category:'Vegan', price:13.8, image:'https://images.unsplash.com/photo-1511689660979-10d2b1aada49?auto=format&fit=crop&w=900&q=80', description:'A plant-powered pizza with a creamy cashew drizzle.', ingredients:['Vegan cheese','Spinach','Artichoke','Cashew cream'], badge:'Plant based' }
];
export const getPizza = (id) => pizzas.find((pizza) => pizza.id === id);
